
-- Longin password is: Firstname123!!!
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('bhx@bhx.com','b/PLfIPGZTFGjXuIxcKrxkDbLXpyV+XiQm9x1qgi3n8=','Jms5D6ewyqvvalzbUIJT8Q==','Bin XU',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('aaa@aaa.com','yZDHw83MmmDI+oQ/mk5m4C0IAAQ4xT4UKpT76NZ9XTs=','SvOF9SMQBI3mht1e12Fiaw==','Tom Zhang',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('willima@abc.com','oinHo+bmHTZLCNzsVsQXqqOROsqzNAs9KEwYTN3k0D8=','4LlyFOY4LjDpItSWKyZqyg==','Willima Smith',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Ella@abc.com','ofWa3KojbgRL3p8R0FOw7nWjyEp61agp1qTcui6XmM0=','dbO3WRAMi2puX7OrP9ORfw==','Ella Miller',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Jackson@abc.com','y/10C6iwNhjm9qvjo6e7zhn4amXCaJdeoW17Z7cStX4=','BZtg1tFxewpiOSrXdEGQ9Q==','Jackson Jones',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Avery@abc.com','s+u/l25yS0zjyPfZi6lAB5dvPtiF+0m3FyY6wgSWjbk=','06oKKZ41SlT80aOtK+5TUw==','Avery Garcia',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Scarlett@abc.com','HXEP3vMgBlivcrnr3i9QUwKUbnjYun8AwV8BO/CRyS4=','ME5BbSdukVmleMQpApixiQ==','Scarlett Brown',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Jack@abc.com','o6T4XsKyaK3DKIM7y+cusJwil2NdicaodmPCDtURgm4=','3FtyvwPahehtyO5G53kgKQ==','Jack Davis',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Ellie@abc.com','jK+Y0RWUsqjipHeYvnNWBqe2EaBD0isMBqqodFFtB2A=','ahNZZEo68mLRwIkvdBRzWw==','Ellia Miller',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Wyatt@abc.com','Ahoryx6jZ8W1ZsCw+VeN1lzcBMMXRz1TritUYZGdIQc=','sAq7C9lSkiR2911EoN1CYw==','Wyatt Johnson',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Julian@abc.com','hXfEyoWbR9B23FsXVXg1iZo0CdzgzjwUXJSsBOuAgQo=','7xe+nM1gYWh5meS8H49hYQ==','Julian Martinez',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Lily@abc.com','Tm4p2l+DMFKRunEgdq2HClte0NXHhJ0DjXE03mpgj5o=','hoE/Slp8WUUySDLaJwLO7w==','Lily Smith',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Grayson@abc.com','YwoU28Lg7DoLHyBEJMtyUDseJnEffgdG0CF0MOjT5N0=','P15SjFiDvK1SBlvjx/3Z+Q==','Grayson Hacke',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Lincoln@abc.com','QRRrHQ2XL832vTGISUz7Zq61v+cDa/7OhpwNKdxTv3g=','iPsSwjQnZh4TQOrcSQVXBQ==','Lincoln Dass',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Everly@abc.com','4Q34+E9l+WzHzqyCYcxE/j73QYPve9N6qxSrYoh6nDc=','hK5h7xGKpCf+2OudzRRDRQ==','Everly Datta',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Jemmie@abc.com','xVlJ48MvmnUytLh16ypdpU44HsSJn+ueNwHYMm31e/k=','BxYk5oVLiQpgcx/C+5a5LA==','Jemmie Datz',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Addison@abc.com','jOpNvmJvXTCFC/0ni/9qXY7MdZKtDr2K2UwkyRzReGI=','tAQ9x0bHMC0qp1nGwue3LQ==','Addison Raco',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Willow@abc.com','TQweAQv9gOGQS0G7DKjiuHXTEF0OApAyxR6Z5M/pDys=','sA1h9qlmHv5+nWdhfWo3HQ==','Willow Racy',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Jaxon@abc.com','P+zXRdpCQnATiu51nWyayFXyj3+5uXJcm3+J8EjWtDk=','jD/RrX62gbNPbCb7GExWxA==','Jaxon Rabin',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Ivy@abc.com','bUpmV2vhubZ4MonzrMFxf8RvBEOGSfU/BVnBOmI+RdM=','HOS/Vi5DdnVOrC65Kgp28Q==','Ivy Paci',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Kelly@abc.com','wYPb1CotZr2XP9oerz1VZDzGx0OSU4SRj7NpsGYQXI0=','mcqmu7IIvDG5CAma8Jxb1g==','Kelly Song',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('Helen@abc.com','AYIIdToYrg02dBp1NKMa6HVxp/tmwkuudciNMqVbIjM=','socY+hSgryqcd5m2x2BIPA==','Helen Taylor',CURRENT_TIMESTAMP)
INSERT into [User](Email,HashedPassword,Salt,FullName,JoinedOn) VALUES('test@abc.com','8bA5oEENlGKIFjq+nrp2pRqCWsGXjVNecB7yQX893OI=','3gN/xlo0OKmJuTPKuEX6gw==','Test test',CURRENT_TIMESTAMP)


INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('1','1002','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('2','4000','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('3','503042','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('4','23423','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('5','1002','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('6','4000','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('7','503042','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('8','23423','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('9','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('10','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('11','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('12','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('13','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('14','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('15','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('16','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('17','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('18','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('19','45232','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('20','45232','interset',CURRENT_TIMESTAMP)


INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('1','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('2','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('3','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('4','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('5','1002','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('6','4000','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('7','503042','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('8','23423','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('9','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('10','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('11','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('12','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('13','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('14','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('15','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('16','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('17','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('18','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('19','45232','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('20','45232','salary',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('20','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('20','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('20','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('20','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('20','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('19','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('19','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('19','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('19','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('19','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('18','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('18','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('18','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('18','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('18','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('17','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('17','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('17','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('17','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('17','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('16','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('16','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('16','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('16','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('16','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('15','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('15','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('15','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('15','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('15','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('14','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('14','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('14','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('14','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('14','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('13','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('13','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('13','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('13','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('13','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('12','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('12','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('12','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('12','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('12','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('11','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('11','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('11','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('11','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('11','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('10','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('10','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('10','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('10','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('10','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('9','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('9','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('9','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('9','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('9','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('8','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('8','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('8','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('8','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('8','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('7','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('7','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('7','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('7','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('7','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('6','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('6','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('6','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('6','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('6','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('5','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('5','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('5','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('5','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('5','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('4','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('4','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('4','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('4','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('4','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('3','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('3','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('3','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('3','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('3','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('2','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('2','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('2','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('2','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('2','-876','shopping',CURRENT_TIMESTAMP)

INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('1','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('1','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('1','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('1','-876','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('1','-876','shopping',CURRENT_TIMESTAMP)

-- data for test (id=24)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','10','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','10','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','10','interset',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','100','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','100','salary',CURRENT_TIMESTAMP)
INSERT into Income(UserId,Amount,[Description],IncomeDate) VALUES('24','100','salary',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('24','-10','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('24','-10','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('24','-100','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('24','-100','shopping',CURRENT_TIMESTAMP)
INSERT into Expenditure(UserId,Amount,[Description],ExpDate) VALUES('24','-10','shopping',CURRENT_TIMESTAMP)